var AppConstants = {
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  INITIALIZE_USER:'INITIALIZE_USER',
  UPDATE_USER: "UPDATE_USER",
  ADD_CLASS: "ADD_CLASS",
  REMOVE_CLASS: "REMOVE_CLASS",
  SET_CLASSES: "GET_CLASSES",
  FIREBASE_HOST: 'https://edq.firebaseio.com/'
};

module.exports = AppConstants;